name: pencil_field
description: Widget for pencil / stylus input on different devices and platforms. It is intended
  for any freehand input like signatures or drawings and supports full persistence
  of the input.
version: 0.1.2
homepage: https://github.com/ManfredM/pencil_field

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        default_package: pencil_field
      ios:
        default_package: pencil_field
      web:
        default_package: pencil_field
