name: pencil_field
description: Pencil / stylus interaction (writing & erasing) on different devices and platforms.
  Comes with versioned persistence of input.
version: 0.2.1
homepage: https://github.com/ManfredM/pencil_field

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        default_package: pencil_field
      ios:
        default_package: pencil_field
      web:
        default_package: pencil_field
