name: pencil_field_testing
run-name: ${{ github.actor }} is analyzing & testing the code
on: [push]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
    - run: flutter pub get
    - run: flutter --version
    - run: dart analyze
    - run: mkdir test/resulting_output
    - run: flutter test
