name: pencil_field_testing
run-name: ${{ github.actor }} is analyzing & testing the code
on: [push]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2

    - name: Prepare Flutter environment
      run: |
        flutter pub get
        flutter --version

    - name: Analyze the Dart code
      run: dart analyze

    - name: run 35 unit tests and check if all test pass
      run: |
        mkdir test/resulting_output
        flutter test > test-results.txt
        ls $GITHUB_WORKSPACE
        cat $GITHUB_WORKSPACE/test-results.txt
        if [ "$(grep -c '35 tests passed.' $GITHUB_WORKSPACE/test-results.txt)" -ne 1 ]; then
          echo "One or more tests failed. Please fix the failing tests and try again."
          exit 1
        fi
